---

- name: Check if we already have a Drupal console instance.
  stat: path="/usr/local/bin/drupal"
  register: drupal_console_install

- name: Install Drupal Console.
  get_url:
    url: https://drupalconsole.com/installer
    dest: "/usr/local/bin/drupal"
    mode: 0755
  when: not drupal_console_install.stat.exists

- name: Run Drupal Console init.
  command: >
    /usr/local/bin/drush init -y
  become: true
  become_user: vagrant
  when: not drupal_console_install.stat.exists