---


- name: Copy startup script in place.
  template:
    src: startup.sh.j2
    dest: "/opt/run-parts/sonar"
    owner: root
    group: root
    mode: 0555
    force: yes

- name: Copy landing page section.
  template:
    src: "section.html.j2"
    dest: "{{ ce_vm_webroot }}/includes/sonar.html"
    force: yes

- name: Generate defaut project configuration.
  template:
    src: "{{ project_type }}.properties.j2"
    dest: "{{ project_dir }}/sonar-project.properties"
    force: no