---

- name: Ensure xdebug is installed.
  apt:
    pkg: php-xdebug
    state: present

- name: Ensure host trace/profiling folder exists.
  file:
    path: "{{ local_var_dir }}/php-xdebug"
    state: directory
  
- name: Copy xdebug configuration in place.
  template:
    src: 30-xdebug-dev.ini.j2
    dest: "/etc/php/{{ php_version }}/fpm/conf.d/30-xdebug-dev.ini"
    owner: root
    group: root
    mode: 0644
    force: yes