---

- name: Check if we already have a symfony CLI.
  stat: path="/usr/local/bin/symfony"
  register: symfony_install

- name: Download Symfony installer.
  get_url:
    url: https://symfony.com/installer
    dest: /usr/local/bin/symfony
    mode: 0755
  when: not symfony_install.stat.exists

- name: Check if we already have a codebase.
  stat: path="{{ project_dir }}/{{ webroot }}"
  register: symfony_base
    
- name: Create Symfony codebase if needed.
  command: >
    symfony new {{ request_time }}
    chdir=/tmp
  become: true
  become_user: vagrant
  when: not symfony_base.stat.exists

- name: Move Symfony codebase in place.
  command: >
    rsync -a --no-perms --no-owner --no-group /tmp/{{ request_time }}/ {{ project_dir }}
  when: not symfony_base.stat.exists
  
- name: Remove Symfony var folder.
  file: 
    path: "{{ project_dir }}/var"
    state: absent
  when: not symfony_base.stat.exists
  
- name: Create a var symlink to /tmp.
  file: 
    dest: "{{ project_dir }}/var"
    src: "/tmp"
    state: link
  when: not symfony_base.stat.exists

- name: Change dev IP.
  command: >
    sed -ie 's/127.0.0.1/192.168.56.1/g' "{{ project_dir }}/{{ webroot }}/app_dev.php"
  when: not symfony_base.stat.exists and vagrant_provider == 'virtualbox'
  
- name: Generate default .gitignore.
  template:
    src: gitignore.j2
    dest: "{{ project_dir }}/{{ webroot }}/.gitignore"
  when: not symfony_base.stat.exists