---

- name: Set php version (phar)
  command: "update-alternatives --set phar /usr/bin/phar{{ php_version }}"

- name: Set php version (phar.phar)
  command: "update-alternatives --set phar.phar /usr/bin/phar.phar{{ php_version }}"

- name: Set php version (php)
  command: "update-alternatives --set php /usr/bin/php{{ php_version }}"

- name: Copy php.ini for php cli.
  template:
    src: php.cli.ini.j2
    dest: "/etc/php/{{ php_version }}/cli/php.ini"
    force: yes