---

# Default settings.

############# Project settings. ################################################
# These are typically shared amongst your team for a given project.
################################################################################

####### Base settings.

# Project name. Only use lower alphanumeric chars, no underscore or hyphen.
project_name: default

ce_vm_upstream: yes
ce_vm_upstream_auto_pull: yes

# Project type, can be either drupal, symfony, wordpress pr php_generic.
project_type: drupal

# Webroot, relative to project.
# Symfony usually expect this to be "web".
webroot: www

####### Software settings.

# PHP version. Can be one of 5.5, 5.6, 7.0.
php_version: 7.0

# Database engine. Can be one of mysql, mariadb or percona-server (recommended)
mysql_engine: percona-server

# NodeJS version. Either 4.x or 6.x.
nodejs_version: ''

# Whether to install MkDocs documentation generator on app-vm.
mkdocs: no

# Whether to install Apache Solr.
solr: no
  
# Whether to install the Selenium test framework.
selenium: no
# Display manager to use with Selenium. Can be either 
# - XVFB: light headless driver
# - VNC: heavier, but provides visual feedback.
selenium_display_manager: XVFB

# Only Nginx is currently supported,
# but you can disable it if you want to
# setup the webserver by yourself.
webserver: nginx

# Extra Debian packages to install on the App vm.
app_extra_packages: ''
#app_extra_packages:
#  - "php{{ php_version }}-ldap"
#  - "php{{ php_version }}-sqlite"
#  - "ruby"
  
# Extra Debian packages to install on the DB vm.
db_extra_packages: ''
#db_extra_packages:
#  - "sqlite"

# Databases to import from dumps on first provisioning.
# Each item consists of 
# - name of database to create
# - source for the dump, relative to the root of the repository.
# Set the source to an empty string if you want to just create an empty db.
db_dumps: ''
#db_dumps:
#  - { name: "legacy", source: "db/legacy.sql" }
#  - { name: "external", source: "db/external-2017.sql" }
#  - { name: "empty_dummy", source: "" }

############# Development settings. ################################################
# These can vary for each developer, and should normally be overriden
# individually in ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
################################################################################

# Enable xdebug for PHP-FPM
php_xdebug: yes

# Enable blackfire for PHP
php_blackfire: no

# Agent server id and token.
# You can find those at https://blackfire.io/account.
php_blackfire_agent_server_id: ''
php_blackfire_agent_server_token: ''
php_blackfire_agent_client_id: ''
php_blackfire_agent_client_token: ''

# Mail delivery.
# All outgoing mail is aliased to the local "vagrant" user.
# The delivery can adopt one of 3 behaviors:
# - local: email is kept locally on the guest vm, using the standard mbox.
#   Use vagrant ssh and the "mail" command to read emails.
# - discard: email is sent to /dev/null and not accessible at all.
#   Use this if your app generates a large amount of mail you don't need,
#   to prevent the virtual disk to grow quickly.
# - host: emails are rerouted to the shared var/Maildir folder, as .eml files.
#   You can then read emails on your host using the mail client of your choice.
mail_delivery: host

# Composer token for github. You typically would not set it here,
# but use ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
composer_github_oauth_token: ''

############# Docker settings. ################################################
# These can vary for each developer, and should normally be overriden
# individually in ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
################################################################################

# Apt shared cache. This stores apt archives in a common mounted volume,
# similar to what the 'vagrant-cachier' plugin does.
# It does save a bit of download time for provisioning on slow network
# connections.
use_apt_cache: yes

# Networking settings.
# You will need to change your hosts file
# if you change from defaults.
net_subnet: 192.168.56.0/24
net_gateway: 192.168.56.1
net_app_ip: 192.168.56.2
net_db_ip: 192.168.56.3
net_proto_ip: 192.168.56.4
net_log_ip: 192.168.56.5
# Port forwarding and SSH.
# We do our best to try and use the suitable settings
# based on your host OS. However, some more advanced
# setup or port conflicts might require you to manually
# edit those. 
# SSH port for vagrant to use. 
# It must match what is forwarded to port 22 below.
docker_app_ssh_port: auto
#docker_app_ssh_port: 22202
# Ports to forward from the host to the guest,
# in "host:guest" format.
# Be sure the host port is free. Typically port 80
# on your host might be already used by an Apache
# instance.
# Leave it to auto and we will try to use
# the most suitable solution based on your OS.
docker_app_fwd_ports: auto
# docker_app_fwd_ports:
#  # SSH
#  - "{{ net_app_ip }}:{{ docker_app_ssh_port }}:22"
#  # Web server
#  - "{{ net_app_ip }}:80:80"
#  - "{{ net_app_ip }}:443:443"
#  # VNC
#  - "{{ net_app_ip }}:5999:5999"
#  # Mkdocs
#  - "{{ net_app_ip }}:8000:8000"

docker_db_ssh_port: auto
# docker_db_ssh_port: 22203
docker_db_fwd_ports: auto
# docker_db_fwd_ports:
# # SSH
#  - "{{ net_db_ip }}:{{ docker_db_ssh_port }}:22"
#  # MySQL
#  - "{{ net_db_ip }}:3306:3306"
#  # Tomcat
#  - "{{ net_db_ip }}:8080:8080"

docker_proto_ssh_port: auto
#docker_proto_ssh_port: 22204
docker_proto_fwd_ports: auto
# docker_proto_fwd_ports:
# # SSH
#  - "{{ net_proto_ip }}:{{ docker_proto_ssh_port }}:22"
#  # Server
#  - "{{ net_proto_ip }}:80:80"

docker_log_ssh_port: auto
#docker_log_ssh_port: 22205
docker_log_fwd_ports: auto
# docker_log_fwd_ports:
# # SSH
#  - "{{ net_log_ip }}:{{ docker_log_ssh_port }}:22"
#  # Server
#  - "{{ net_log_ip }}:80:80"


# Vagrant user uid and group gid. 
# You normally don't have to change this,
# the only exception being Docker on a 
# Linux host, where it should match your 
# actual user uid/gid.
docker_vagrant_user_uid: 1000
docker_vagrant_group_gid: 1000

# Replace the native Volume mount with a Unison based synchronisation.
docker_mirror: no

# Privileged mode for containers. 
# If left on "auto", defaults to "false",
# unless you need Tomcat/Solr and you're on a Mac.
# You can "force" it to either "true" or "false".
docker_app_privileged: auto
docker_db_privileged: auto
docker_proto_privileged: auto
docker_log_privileged: auto
