---

# Default settings.

############# Project settings. ################################################
# These are typically shared amongst your team for a given project.
################################################################################

####### Base settings.

# Project name. Only use lower alphanumeric chars, no underscore or hyphen.
project_name: default

ce_vm_upstream: yes
ce_vm_upstream_auto_pull: yes

# Project type, can be either drupal, symfony, wordpress pr php_generic.
project_type: drupal

# Webroot, relative to project.
# Symfony usually expect this to be "web".
webroot: www

####### Software settings.

# PHP version. Can be one of 5.5, 5.6, 7.0.
php_version: 7.0

# Database engine. Can be one of mysql, mariadb or percona-server (recommended)
mysql_engine: percona-server

# NodeJS version. Either 4.x or 6.x.
nodejs_version: ''

# Whether to install memcached on the DB vm.
memcached: yes

# Whether to install Redis on the DB vm.
redis: no

# Whether to install MkDocs documentation generator on app-vm.
mkdocs: no

# Whether to install Apache Solr.
solr: no
  
# Whether to install the Selenium test framework.
selenium: no
# Display manager to use with Selenium. Can be either 
# - XVFB: light headless driver
# - VNC: heavier, but provides visual feedback.
selenium_display_manager: XVFB

# Only Nginx is currently supported,
# but you can disable it if you want to
# setup the webserver by yourself.
webserver: nginx

# Extra Debian packages to install on the App vm.
app_extra_packages: ''
#app_extra_packages:
#  - "php{{ php_version }}-ldap"
#  - "php{{ php_version }}-sqlite"
#  - "ruby"
  
# Extra Debian packages to install on the DB vm.
db_extra_packages: ''
#db_extra_packages:
#  - "sqlite"

# Databases to import from dumps on first provisioning.
# Each item consists of 
# - name of database to create
# - source for the dump, relative to the root of the repository.
# Set the source to an empty string if you want to just create an empty db.
db_dumps: ''
#db_dumps:
#  - { name: "legacy", source: "db/legacy.sql" }
#  - { name: "external", source: "db/external-2017.sql" }
#  - { name: "empty_dummy", source: "" }

############# Development settings. ################################################
# These can vary for each developer, and should normally be overriden
# individually in ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
################################################################################

# Enable xdebug for PHP-FPM
php_xdebug: yes

# Enable blackfire for PHP
php_blackfire: no

# Agent server id and token.
# You can find those at https://blackfire.io/account.
php_blackfire_agent_server_id: ''
php_blackfire_agent_server_token: ''
php_blackfire_agent_client_id: ''
php_blackfire_agent_client_token: ''

# Mail delivery.
# All outgoing mail is aliased to the local "vagrant" user.
# The delivery can adopt one of 3 behaviors:
# - local: email is kept locally on the guest vm, using the standard mbox.
#   Use vagrant ssh and the "mail" command to read emails.
# - discard: email is sent to /dev/null and not accessible at all.
#   Use this if your app generates a large amount of mail you don't need,
#   to prevent the virtual disk to grow quickly.
# - host: emails are rerouted to the shared var/Maildir folder, as .eml files.
#   You can then read emails on your host using the mail client of your choice.
mail_delivery: host

# Composer token for github. You typically would not set it here,
# but use ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
composer_github_oauth_token: ''

############# Provider settings. ################################################
# These can vary for each developer, and should normally be overriden
# individually in ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
################################################################################

# Provider. Either virtualbox (safest) or docker (experimental).
vagrant_provider: virtualbox

####### VirtualBox specific settings.

# Shared folder mode. Can be one of:
# - virtualbox (default if empty): Safest choice, should work for all hosts,
#   but poor performances.
# - nfs: good performances, supported on Linux and Mac OS hosts only.
#   This mode is usually the best trade-off between perf and usability.
# - rsync: best performances, but one-way (host > guest) only, 
#   which is unpractical for most projects. Require rsync on the host.
#   WARNING: This mode is not suitable for launching a new project,
#   as files created during provisioning would only be present on the guest.
# @see https://www.vagrantup.com/docs/synced-folders/
vbox_synced_folder_type: ''
#vbox_synced_folder_type: nfs

# Custom sharing options, enterly overrides the defaults above.
vbox_synced_folder_options_overrides: ''

# Memory and CPU to use for the app VM.
# The more RAM, the better. Be simply aware not to excess 
# what is available on your host.
vbox_app_memory: 2048
# While in theory giving access to all of your cores to the VM
# should make it faster, in practice this is not the case.
# From our tests, allocating  more than one CPU is effect-less at best,
# and even degrades performances in most cases.
vbox_app_cpus: 1

# Memory and CPU to use for the db VM.
vbox_db_memory: 2048
vbox_db_cpus: 1

####### Docker specific settings.

# SSH port for vagrant to use. 
# It must match what is forwarded to port 22 below.
docker_app_ssh_port: 22202
# Ports to forward from the host to the guest,
# in "host:guest" format.
# Be sure the host port is free. Typically port 80
# on your host might be already used by an Apache
# instance on mac OS X.
docker_app_fwd_ports:
 - "22202:22"
 # Web server
 - "80:80"
 - "443:443"
 # VNC
 - "5999:5999"
 # Selenium
 - "4444:4444"
 # Mkdocs
 - "8000:8000"

docker_db_ssh_port: 22203
docker_db_fwd_ports: 
 - "22203:22"
 # MySQL
 - "3306:3306"
 # Memcached
 - "11211:11211"
 # Tomcat
 - "8080:8080"

# Vagrant user uid and group gid. 
# You normally don't have to change this,
# the only exception being Docker on a 
# Linux host, where it should match your 
# actual user uid/gid.
docker_vagrant_user_uid: 1000
docker_vagrant_group_gid: 1000


# Networking settings.
# You will need to change your hosts file
# if you change from defaults.
net_subnet: 192.168.56.0/24
net_gateway: 192.168.56.1
net_app_ip: 192.168.56.2
net_db_ip: 192.168.56.3
