---

# Default settings.

############# Project settings. ################################################
# These are typically shared amongst your team for a given project.
################################################################################

####### Base settings.

# Project name. Only use lower alphanumeric chars, no underscore or hyphen.
project_name: default

ce_vm_upstream_auto_pull: yes

# Project type, can be either drupal, symfony, wordpress pr php_generic.
project_type: drupal

# Webroot, relative to project.
# Symfony usually expect this to be "web".
webroot: www

# Services.
services:
  - app
  - log
  - memcached
  - mkdocs
  - mysql
  - solr

#  - mkdocs

# Whether to install Apache Solr.
solr: no
  
# Whether to install the Selenium test framework.
selenium: no
# Display manager to use with Selenium. Can be either 
# - XVFB: light headless driver
# - VNC: heavier, but provides visual feedback.
selenium_display_manager: XVFB

############# Development settings. ################################################
# These can vary for each developer, and should normally be overriden
# individually in ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
################################################################################

# Enable xdebug for PHP-FPM
php_xdebug: yes

# Enable blackfire for PHP
php_blackfire: no

# Agent server id and token.
# You can find those at https://blackfire.io/account.
php_blackfire_agent_server_id: ''
php_blackfire_agent_server_token: ''
php_blackfire_agent_client_id: ''
php_blackfire_agent_client_token: ''

# Mail delivery.
# All outgoing mail is aliased to the local "vagrant" user.
# The delivery can adopt one of 3 behaviors:
# - local: email is kept locally on the guest vm, using the standard mbox.
#   Use vagrant ssh and the "mail" command to read emails.
# - discard: email is sent to /dev/null and not accessible at all.
#   Use this if your app generates a large amount of mail you don't need,
#   to prevent the virtual disk to grow quickly.
# - host: emails are rerouted to the shared var/Maildir folder, as .eml files.
#   You can then read emails on your host using the mail client of your choice.
mail_delivery: host

# Composer token for github. You typically would not set it here,
# but use ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
composer_github_oauth_token: ''

############# Docker settings. ################################################
# These can vary for each developer, and should normally be overriden
# individually in ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
################################################################################

# Apt shared cache. This stores apt archives in a common mounted volume,
# similar to what the 'vagrant-cachier' plugin does.
# It does save a bit of download time for provisioning on slow network
# connections.
use_apt_cache: yes

# Networking settings.
# You will need to change your hosts file
# if you change from defaults.
net_subnet: 192.168.56.0/24
net_gateway: 192.168.56.1

# Vagrant user uid and group gid. 
# You normally don't have to change this,
# the only exception being Docker on a 
# Linux host, where it should match your 
# actual user uid/gid.
docker_vagrant_user_uid: 1000
docker_vagrant_group_gid: 1000

# Replace the native Volume mount with a Unison based synchronisation.
docker_mirror: no