---

############# Project settings for the "mysql" service. ##########################
# These are typically shared amongst your team for a given project.
################################################################################

# Extra Debian packages to install.
apt_extra_packages: ''
#apt_extra_packages:
#  - "ruby"
#  - "mysql-client"
  
# Databases to import from dumps on first provisioning.
# Each item consists of 
# - name of database to create
# - source for the dump, relative to the root of the repository.
# Set the source to an empty string if you want to just create an empty db.
db_dumps: ''
#db_dumps:
#  - { name: "legacy", source: "db/legacy.sql" }
#  - { name: "external", source: "db/external-2017.sql" }
#  - { name: "empty_dummy", source: "" }

############# Docker settings. #################################################
# These can vary for each developer, and should normally be overriden
# individually in ~/.CodeEnigma/ce-vm/ce-vm-custom/config_log.yml instead.
################################################################################

# Apt shared cache. This stores apt archives in a common mounted volume,
# similar to what the 'vagrant-cachier' plugin does.
# It does save a bit of download time for provisioning on slow network
# connections.
use_apt_cache: yes

# Networking settings.
# You will need to change your hosts file
# if you change from defaults.
net_ip: 192.168.56.3

# Ports to forward from the host to the guest,
# in "host:guest" format.
# Be sure the host port is free. Typically port 80
# on your host might be already used by an Apache
# instance.
# Leave it to auto and we will try to use
# the most suitable solution based on your OS.
net_fwd_ports_mac_os:
  - "{{ net_ip }}:3306:3306"
#net_fwd_ports_linux:
#  - 3306:3307
#net_fwd_ports_windows:
#  - 3306:3307

# Docker extra options. These varies based on host OS.
#docker_extra_args_mac_os:
#  - '--privileged=TRUE'
#  - '--cap-add=SYS_PTRACE'
#docker_extra_args_linux:
#  - '--privileged=TRUE'
#  - '--cap-add=SYS_PTRACE'
#docker_extra_args_windows:
#  - '--privileged=TRUE'
#  - '--cap-add=SYS_PTRACE'