---

############# Project settings. ################################################
# These are typically shared amongst your team for a given project,
# and should be committed in git alongside your project.
# 
# See http://ce-vm.readthedocs.io/en/latest/config/config/ on possible config
# files location and variable precedence.
# 
################################################################################

####### Base settings.

# Project name. Only use lower alphanumeric chars, no underscore or hyphen.
project_name: default

# Project type, can be either drupal, symfony, wordpress pr php_generic.
project_type: drupal

# Webroot, relative to project folder.
webroot: www

# Symfony local dev environment.
symfony_local_env: dev

####### Services/containers.
services:
  - fpm
  - memcached
  - mkdocs
  - mysql
  - nginx
  - nodejs
  - redis
  - solr
  - haproxy
  - nightwatch
  - cli

####### Networking.

# You will need to change your hosts file if you change from defaults.
net_base: 192.168.57
net_subnet: "{{ net_base }}.0/24"
net_gateway: "{{ net_base }}.1"
domain: 'ce-vm.local'

####### Common settings.

php_version: 7.1

# Extra Debian packages to install.
apt_extra_packages: ''

############# Development settings. ################################################
# These can vary for each developer, and should normally be overriden
# individually in ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
################################################################################

ce_vm_version: "5.0.1"

# Turn automatic update of the core stack ON/OFF.
# Useful for offline use.
ce_vm_auto_update: yes

# File mount binding.
volume_type: native

# Enable xdebug for PHP
php_xdebug: yes

# Enable blackfire for PHP
php_blackfire: no

# Agent server id and token.
# You can find those at https://blackfire.io/account.
php_blackfire_agent_server_id: ''
php_blackfire_agent_server_token: ''
php_blackfire_agent_client_id: ''
php_blackfire_agent_client_token: ''

# Mail delivery.
# All outgoing mail is aliased to the local "vagrant" user.
# The delivery can adopt one of 3 behaviors:
# - local: email is kept locally on the guest vm, using the standard mbox.
#   Use vagrant ssh and the "mail" command to read emails.
# - discard: email is sent to /dev/null and not accessible at all.
#   Use this if your app generates a large amount of mail you don't need,
#   to prevent the virtual disk to grow quickly.
# - host: emails are rerouted to the shared var/Maildir folder, as .eml files.
#   You can then read emails on your host using the mail client of your choice.
mail_delivery: host

# Composer token for github. You typically would not set it here,
# but use ~/.CodeEnigma/ce-vm/ce-vm-custom/config.yml instead.
composer_github_oauth_token: ''

# Vagrant user uid and group gid. 
# You normally don't have to change this,
# the only exception being Docker on a 
# Linux host, where it should match your 
# actual user uid/gid.
#docker_vagrant_user_uid: 1000
#docker_vagrant_group_gid: 1000
