---

site_name: ce-vm

repo_url: https://github.com/codeenigma/ce-vm

theme: readthedocs

pages:
  - About: index.md
  - Getting started:
    - Installation: get-started/install.md
    - Usage: get-started/usage.md
  - Customisation:
    - Configuration: config/config.md
    - Ansible customization: config/ansible.md
  - Stack details:
    - The "App" instance: stack/app.md
    - The "Database" instance: stack/db.md
    - Components:
      - NGINX: stack/components/nginx.md
      - PHP: stack/components/php.md
      - Postfix: stack/components/postfix.md
      - Selenium: stack/components/selenium.md
      - Solr: stack/components/solr.md
  - Tips & recipes:
      - Wrapper scripts: tips/scripts.yml
      - SSH: tips/ssh.yml
  - Topics:
      - Upgrades: topics/upgrades.md
      - Shared mounts: topics/shared-mounts.md
      - Security: topics/security.md
      - Networking: topics/networking.md
