---

mkdocs_listen_port: 8000

docker_image: "pmce/ce-vm-mkdocs:{{ ce_vm_version }}"
net_ip: "{{ net_base }}.70"
net_fwd_ports_mac_os:
  - "{{ net_ip }}:{{ mkdocs_listen_port }}:{{ mkdocs_listen_port }}"
