---
# Install rsylog

- name: Ensure rsyslog is installed.
  apt:
    pkg: rsyslog
    state: present
    
- name: Copy startup script in place.
  template:
    src: startup.sh.j2
    dest: "/opt/run-parts/rsyslog"
    owner: root
    group: root
    mode: 0555
    force: yes