---

- name: Check if we already have a codebase.
  stat: path="{{ project_dir }}/{{ webroot }}"
  register: ce_drupal_codebase

- name: Check if we already have a composer file.
  stat: path="{{ project_dir }}/composer.json"
  register: ce_drupal_composer

- name: Generates composer.json file if none exist.
  template:
    src: composer.json.j2
    dest: "{{ project_dir }}/composer.json"
    owner: vagrant
  when: 
    - not ce_drupal_codebase.stat.exists
    - not ce_drupal_composer.stat.exists
    
- name: Require Drupal dependencies.
  composer:
    command: require
    arguments: "{{ item }} --sort-packages"
    working_dir: "{{ project_dir }}"
  with_items:
    - "composer/installers"
    - "drupal-composer/drupal-scaffold"
    - "drupal/core"
    - "drupal/config_ignore"
    - "drupal/config_installer"
  become: true
  become_user: vagrant
  when: 
  - not ce_drupal_codebase.stat.exists
  - not ce_drupal_composer.stat.exists

- name: Check if we now have a composer file.
  stat: path="{{ project_dir }}/composer.json"
  register: ce_drupal_composer_new
  
- name: Composer install Drupal.
  composer:
    command: install
    working_dir: "{{ project_dir }}"
  become: true
  become_user: vagrant
  when: ce_drupal_composer_new.stat.exists
  
- name: Generate default .gitignore (if needed).
  template:
    src: gitignore.j2
    dest: "{{ project_dir }}/{{ webroot }}/.gitignore"
  
- name: Generates ce-vm.settings.php file.
  template:
    src: ce-vm.settings.php.j2
    dest: "{{ project_dir }}/{{ webroot }}/sites/default/ce-vm.settings.php"
    force: no

- name: Check if we already have a settings.php file.
  stat: path="{{ project_dir }}/{{ webroot }}/sites/default/settings.php"
  register: drupal_install
  
- name: Symlink settings.php if needed.
  file:
    src: "./ce-vm.settings.php"
    dest: "{{ project_dir }}/{{ webroot }}/sites/default/settings.php"
    state: link
  when: not drupal_install.stat.exists 
  
- name: Install Drupal.
  command: drush si -y -r "{{ project_dir }}/{{ webroot }}"
  when: not drupal_install.stat.exists

- name: Clear Drupal caches.
  command: drush cr -y -r "{{ project_dir }}/{{ webroot }}"
  when: not ce_drupal_codebase.stat.exists

- name: Set target ownership/permissions.
  file: 
    path: "/vagrant"
    owner: vagrant
    group: www-data
    recurse: yes
    mode: 0777
    state: directory