---

- name: Add Sury repository key for PHP 5.5, 5.6, 7.0 or 7.1.
  apt_key: url=https://packages.sury.org/php/apt.gpg state=present

- name: Add Sury repository.
  apt_repository: repo='deb https://packages.sury.org/php/ jessie main' state=present

- name: Pin Sury packages.
  template:
    src: sury.pref.j2
    dest: "/etc/apt/preferences.d/sury.pref"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Install PHP packages.
  apt: "name={{ item }} state=present"
  with_items:
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-dev"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-imap"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-opcache"
    - "php{{ php_version }}-soap"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-zip"
    - "php-memcached"
    - "php-redis"