---
# Install Yarn

- name: Add repository key for Yarn repository.
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg state=present
  
- name: Add repository for Yarn.
  apt_repository: repo='deb https://dl.yarnpkg.com/debian/ stable main' state=present
  
- name: Ensure Yarn is installed.
  apt:
    pkg: "yarn"
    state: present    
    
- name: Create Yarn shared cache dir if needed.
  file:
    path: '{{ shared_cache_dir }}/yarn'
    owner: 'vagrant'
    group: 'root'
    state: directory
    
- name: Set Yarn cache location.
  template:
    src: yarnrc.j2
    dest: "/home/vagrant/.yarnrc"