---

- name: Install dependencies.
  apt: "name={{ item }} state=present"
  with_items:
    - "ruby"
    - "bundler"
    - "gcc"
    - "make"

- name: Install Jekyll
  gem:
    name: jekyll
    state: present

- name: Check if we already have a codebase.
  stat: path="{{ project_dir }}/{{ webroot }}"
  register: jekyll_install
  
- name: Generate basic structure.
  command: jekyll new --source "{{ project_dir }}/src" --destination "{{ project_dir }}/{{ webroot }}"
  become: true
  become_user: vagrant
  when: not jekyll_install.stat.exists