---

- name: Create apt cache dir if needed.
  file:
    path: '{{ shared_cache_dir }}/apt'
    state: directory

- name: Create apt archive dir if needed.
  file:
    path: '{{ shared_cache_dir }}/apt/archives'
    state: directory

- name: Move apt cache to shared dir.
  template:
    src: "apt-cache.j2"
    dest: "/etc/apt/apt.conf.d/90ce-vm-aptcache"
    owner: 'root'
    group: 'root'
    force: yes

- name: Clean up startup scripts folder.
  file:
    path: '/opt/run-parts'
    state: absent

- name: (Re-)Create startup scripts folder.
  file:
    path: '/opt/run-parts'
    state: directory