---

- name: Create apt archive dir if needed.
  file:
    path: '{{ shared_cache_dir }}/apt/archives'
    state: directory
    recurse: yes
  when: use_apt_cache

- name: Move apt cache to shared dir.
  template:
    src: "apt-cache.j2"
    dest: "/etc/apt/apt.conf.d/90ce-vm-aptcache"
    owner: 'root'
    group: 'root'
    force: yes
  when: use_apt_cache

- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Clean up startup scripts folder.
  file:
    path: '/opt/run-parts'
    state: absent

- name: (Re-)Create startup scripts folder.
  file:
    path: '/opt/run-parts'
    state: directory

- name: Set ce-vm webroot.
  set_fact: ce_vm_webroot="{{ local_var_www_dir }}/ce-vm"

- name: Create ce-vm webroot and includes directory.
  file:
    path: "{{ ce_vm_webroot }}/includes"
    state: directory
    recurse: yes