---

- name: Create apt cache dir if needed.
  file:
    path: '{{ shared_cache_dir }}/apt'
    state: directory

- name: Move apt cache to shared dir.
  template:
    src: "apt-cache.j2"
    dest: "/etc/apt/apt.conf.d/90ce-vm-aptcache"
    owner: 'root'
    group: 'root'
    force: yes

- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=86400

- name: Update all packages to the latest version
  apt:
    upgrade: dist
    force: yes

- name: Get base tools.
  apt: "name={{ item }} state=latest"
  with_items:
    - apt-transport-https
    - curl
    - python-apt
    - python-pycurl
    - build-essential
    - sudo
    - unzip
    - vim
    - software-properties-common
    - wget
    - cron