---

- name: Add repository key for PHP 5.5, 5.6, 7.0 or 7.1.
  apt_key: url=https://packages.sury.org/php/apt.gpg state=present

- apt_repository: repo='deb https://packages.sury.org/php/ jessie main' state=present

- name: Install PHP packages.
  apt: "name={{ item }} state=latest"
  with_items:
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-dev"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-imap"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-opcache"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-memcached"

- name: Ensure php-fpm is restarted.
  service: name=php{{ php_version }}-fpm state=restarted enabled=yes