---

- name: Add Sury repository key for PHP 5.5, 5.6, 7.0 or 7.1.
  apt_key: url=https://packages.sury.org/php/apt.gpg state=present

- name: Add Sury repository.
  apt_repository: repo='deb https://packages.sury.org/php/ jessie main' state=present

- name: Install PHP packages.
  apt: "name={{ item }} state=present"
  with_items:
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-dev"
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-imap"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-memcached"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-opcache"
    - "php{{ php_version }}-redis"
    - "php{{ php_version }}-soap"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-zip"

- name: Copy php.ini for php-fpm.
  template:
    src: php.fpm.ini.j2
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"

- name: Copy php.ini for php cli.
  template:
    src: php.cli.ini.j2
    dest: "/etc/php/{{ php_version }}/cli/php.ini"
    force: yes

- name: Create log directory.
  file:
    path: "/var/log/php"
    owner: www-data
    group: www-data
    mode: 0777
    state: directory

- name: Copy startup script in place.
  template:
    src: startup.sh.j2
    dest: "/opt/run-parts/php"
    owner: root
    group: root
    mode: 0555
    
- name: Copy landing page section.
  template:
    src: "section.html.j2"
    dest: "{{ ce_vm_webroot }}/includes/php.html"
    force: yes
    
- name: Copy phpinfo vhost in place.
  template:
    src: vhost.j2
    dest: "/etc/nginx/sites-enabled/php.conf"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Create PHP info webroot.
  file:
    dest: "{{ local_var_www_dir }}/php"
    state: directory
    
- name: Create PHP info page.
  template:
    src: "index.php.j2"
    dest: "{{ local_var_www_dir }}/php/index.php"