---
  
- name: Create Unison download shared cache dir if needed.
  file:
    path: '{{ shared_cache_dir }}/unison'
    state: directory

- name: Download Unison
  get_url:
    url: "https://www.codeenigma.com/sites/default/files/unison-{{ unison_version }}"
    dest: "{{ shared_cache_dir }}/unison/unison-{{ unison_version }}"

- name: Download Unison FS Monitor
  get_url:
    url: "https://www.codeenigma.com/sites/default/files/unison-fsmonitor-{{ unison_version }}"
    dest: "{{ shared_cache_dir }}/unison/unison-fsmonitor-{{ unison_version }}"
 
- name: Copy Unison to local file system.
  copy:
    dest: '/usr/local/bin/unison'
    src: "{{ shared_cache_dir }}/unison/unison-{{ unison_version }}"
    mode: 0655

- name: Copy Unison FS Monitor to local file system.
  copy:
    dest: '/usr/local/bin/unison-fsmonitor'
    src: "{{ shared_cache_dir }}/unison/unison-fsmonitor-{{ unison_version }}"
    mode: 0655

- name: Prepare ignore list.
  set_fact: unison_ignore_string={{ unison_ignore | wrap | join(" -ignore ") }}

- name: Initial data sync
  shell: flock /tmp/unison.lock /usr/local/bin/unison -batch -owner -group -ignore {{ unison_ignore_string }} -prefer /.ce-vm-mirror/vagrant /.ce-vm-mirror/vagrant /vagrant

- name: Set target ownership/permissions.
  file: 
    path: "/vagrant"
    owner: vagrant
    group: www-data
    recurse: yes
    mode: 0777
    state: directory

- name: Copy startup script in place.
  template:
    src: startup.sh.j2
    dest: "/opt/run-parts/unison"
    owner: root
    group: root
    mode: 0555
    force: yes
