---

- name: Check if we already have a composer instance.
  stat: path="/usr/local/bin/composer"
  register: comp_install

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not comp_install.stat.exists

- name: Run Composer installer.
  command: >
    php composer-installer.php
    chdir=/tmp
  when: not comp_install.stat.exists

- name: Move Composer into globally-accessible location.
  shell: >
    mv /tmp/composer.phar /usr/local/bin/composer
  when: not comp_install.stat.exists
  
- name: Ensure composer directory exists.
  file:
    path: '/home/vagrant/.composer'
    owner: 'vagrant'
    group: 'vagrant'
    state: directory

- name: Add GitHub OAuth token for Composer (if configured).
  template:
    src: "auth.json.j2"
    dest: "/home/vagrant/.composer/auth.json"
    owner: 'vagrant'
    group: 'vagrant'
    force: yes
  when: composer_github_oauth_token != ''
