---

- name: Add key for Blackfire repository.
  apt_key: url=https://packagecloud.io/gpg.key state=present
  
- name: Add repository for Blackfire.
  apt_repository: repo='deb http://packages.blackfire.io/debian any main' state=present
    
- name: Ensure Blackfire agent is installed.
  apt:
    pkg: "blackfire-agent"
    state: present
    
- name: Ensure Blackfire probe is installed.
  apt:
    pkg: "blackfire-php"
    state: present
    
- name: Generate agent server configuration.
  template:
    src: agent.j2
    dest: "/etc/blackfire/agent"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Generate agent client configuration.
  template:
    src: blackfire.ini.j2
    dest: "/home/vagrant/.blackfire.ini"
    owner: vagrant
    group: vagrant
    mode: 0644
    force: yes
    
- name: Copy startup script in place.
  template:
    src: startup.sh.j2
    dest: "/opt/run-parts/blackfire"
    owner: root
    group: root
    mode: 0555
    force: yes