---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - set_fact: request_time="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
    - set_fact: local_var_dir="{{ project_dir }}/{{ vm_dir }}/var"
    - set_fact: local_var_www_dir="{{ local_var_dir }}/www"
    - set_fact: local_var_vm_dir="{{ local_var_dir }}/{{ inventory_hostname }}"
    
    - include_vars: "{{ item }}"
      with_fileglob: "{{ config_files }}"
    
    - name: Run init tasks
      import_tasks: tasks/init.yml

  roles:
    
    - { role: ce.unison, when: docker_mirror }
    - { role: ce.nginx }
    - { role: ce.ce_vm }
    - { role: ce.postfix }
    - { role: ce.php }
    - { role: ce.composer }
    - { role: ce.php_messdetector }
    - { role: ce.php_codesniffer, when: not project_type == 'drupal' }
    - { role: ce.php_xdebug, when: php_xdebug }
    - { role: ce.php_blackfire, when: php_blackfire }
    - { role: ce.mkdocs, when: mkdocs }
    - { role: ce.nodejs, when: nodejs_version == '4.x' or nodejs_version == '6.x'}
    - { role: ce.drush, when: project_type == 'drupal' }
    - { role: ce.drupal_console, when: project_type == 'drupal' }
    - { role: ce.drupal_coder, when: project_type == 'drupal' }
    - { role: ce.drupal, when: project_type == 'drupal' }
    - { role: ce.symfony, when: project_type == 'symfony' }
    - { role: ce.wp_cli, when: project_type == 'wordpress' }
    - { role: ce.wordpress, when: project_type == 'wordpress' }
    - { role: ce.php_generic, when: project_type == 'php_generic' }
    - { role: ce.selenium, when: selenium }

  tasks:
    # Install extra packages.
    - name: Install additional extra packages.
      apt: "name={{ item }} state=present"
      with_items: "{{ app_extra_packages | list }}"
      when: app_extra_packages | length