---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - name: Run init tasks
      import_tasks: tasks/init.yml

  roles:
    
    - { role: ce.rsyslog_client }
    - { role: ce.unison, when: docker_mirror }
    - { role: ce.nginx }
    - { role: ce.postfix }
    - { role: ce.ce_vm }
    - { role: ce.nodejs, nodejs_version: 8.x}
    - { role: ce.drupal, when: project_type == 'drupal' }
    - { role: ce.symfony, when: project_type == 'symfony' }
    - { role: ce.wp_cli, when: project_type == 'wordpress' }
    - { role: ce.wordpress, when: project_type == 'wordpress' }
    - { role: ce.php_generic, when: project_type == 'php_generic' }
    - { role: ce.selenium, when: selenium }

  tasks:
    # Install extra packages.
    - name: Install additional extra packages.
      apt: "name={{ item }} state=present"
      with_items: "{{ apt_extra_packages | list }}"
      when: apt_extra_packages | length