---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - name: Run init tasks
      import_tasks: tasks/init.yml

  roles:
    - { role: rsyslog_client }
    - { role: postfix }

  post_tasks:
    
    - name: Apply overrides
      import_tasks: tasks/override.yml
