---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - name: Run init tasks
      import_tasks: tasks/init.yml
    
  roles:

    - { role: php-cli, php_version: 7.1 }
    - { role: cevm }
    - { role: nfs_server }