---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - name: Run init tasks
      import_tasks: tasks/init.yml

  roles:
    - { role: unison, when: volume_type == 'unison' }
    - { role: php-cli }
    - { role: xdebug, php_build_type: cli }
    - { role: blackfire }
    - { role: rsyslog_client }
    - { role: postfix }
    - { role: composer }
    - { role: drupal, when: project_type == 'drupal' }
    - { role: symfony3, when: project_type == 'symfony3' }
    - { role: symfony4, when: project_type == 'symfony4' }
    - { role: wordpress, when: project_type == 'wordpress' }
    - { role: custom, when: project_type == 'custom' }
    - { role: simplesamlphp, when: simplesamlphp }

  post_tasks:
    
    - name: Apply overrides
      import_tasks: tasks/override.yml
