---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - set_fact: request_time="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
    - set_fact: local_var_dir="{{ project_dir }}/{{ vm_dir }}/var"
    - set_fact: local_var_www_dir="{{ local_var_dir }}/www"
    - set_fact: local_var_vm_dir="{{ local_var_dir }}/{{ inventory_hostname }}"
    
    - include_vars: "{{ item }}"
      with_fileglob: "{{ config_files }}"
    
    - name: Run init tasks
      import_tasks: tasks/init.yml
    
  roles:

    - { role: ce.rsyslog_client }
    - { role: ce.mysql }
    - { role: ce.memcached }
    - { role: ce.redis }
    - { role: ce.solr, when: solr}
    - { role: ce.postfix }

  tasks:
    # Install extra packages.
    - name: Install additional extra packages.
      apt: "name={{ item }} state=present"
      with_items: "{{ db_extra_packages | list }}"
      when: db_extra_packages | length