---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - name: Run init tasks
      import_tasks: tasks/init.yml
    
  roles:
  
    - { role: cron }
    - { role: rsyslog_client }
    - { role: elastic }

  post_tasks:
    
    - name: Apply overrides
      import_tasks: tasks/override.yml

