---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - name: Run init tasks
      import_tasks: tasks/init.yml
    
  roles:
    
    - { role: cron }
    - { role: unison, when: volume_type == 'unison' }
    - { role: rsyslog_client }
    - { role: php-fpm }
    - { role: xdebug, php_build_type: fpm }
    - { role: blackfire }
    - { role: postfix }

  post_tasks:
    
    - name: Apply overrides
      import_tasks: tasks/override.yml
