---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - name: Run init tasks
      import_tasks: tasks/init.yml
    
  roles:

    - { role: ce.rsyslog_client }
    - { role: ce.memcached }
    - { role: ce.postfix }

  tasks:
    # Install extra packages.
    - name: Install additional extra packages.
      apt: "name={{ item }} state=present"
      with_items: "{{ apt_extra_packages | list }}"
      when: apt_extra_packages | length