---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - name: Run init tasks
      import_tasks: tasks/init.yml

  roles:

    - { role: cron }
    - { role: unison, when: volume_type == 'unison' }
    - { role: rsyslog_client }
    - { role: postfix }
    - { role: nodejs, nodejs_version: 8.x}
    - { role: yarn }
    - { role: selenium }
    - { role: nightwatch }

  post_tasks:
    
    - name: Apply overrides
      import_tasks: tasks/override.yml
