---
# Install postfix

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false
  
- name: Ensure postfix is installed.
  apt:
    pkg: postfix
    state: latest

- name: Ensure procmail is installed.
  apt:
    pkg: procmail
    state: latest

- name: Configure postfix main.cf.
  template:
    src: main.cf.j2
    dest: "/etc/postfix/main.cf"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Configure procmail to local.
  file:
    path: "/etc/procmailrc"
    state: absent
  when: mail_delivery == 'guest'

- name: Configure procmail to NULL.
  template:
    src: procmailrc_null.j2
    dest: "/etc/procmailrc"
    owner: root
    group: root
    mode: 0644
    force: yes
  when: mail_delivery == 'discard'

- name: Configure procmail to host directory.
  template:
    src: procmailrc_host.j2
    dest: "/etc/procmailrc"
    owner: root
    group: root
    mode: 0644
    force: yes
  when: mail_delivery == 'host'

- name: Ensure host maildir exists.
  file:
    path: "{{ local_var_dir }}/Maildir"
    state: directory
  when: mail_delivery == 'host'

- name: Manually force postfix stop.
  service: name=postfix state=stopped
  when: vagrant_provider == 'docker'
  
- name: Force postfix pid file removal
  file:
    path: "/var/spool/postfix/pid/master.pid"
    state: absent
  when: vagrant_provider == 'docker'

- name: Ensure postfix is started and enabled to start at boot.
  service: name=postfix state=restarted enabled=yes
