---

- name: Ensure composer directory exists.
  file:
    path: '/home/vagrant/.composer'
    owner: 'vagrant'
    group: 'vagrant'
    state: directory

- name: Add GitHub OAuth token for Composer (if configured).
  template:
    src: "auth.json.j2"
    dest: "/home/vagrant/.composer/auth.json"
    owner: 'vagrant'
    group: 'vagrant'
    force: yes
  when: composer_github_oauth_token != ''

- name: Create composer shared cache dir if needed.
  file:
    path: '{{ shared_cache_dir }}/composer'
    owner: 'vagrant'
    group: 'vagrant'
    state: directory
    
- name: Symlink composer shared cache.
  file:
    path: '/home/vagrant/.composer/cache'
    src: '{{ shared_cache_dir }}/composer'
    owner: 'vagrant'
    group: 'vagrant'
    state: link