---
# Install memcached

- name: Ensure memcached is installed.
  apt:
    pkg: memcached
    state: present
    
- name: Copy memcached configuration in place.
  template:
    src: memcached.conf.j2
    dest: "/etc/memcached.conf"
    owner: root
    group: root
    mode: 0644
    force: yes
    
- name: Ensure memcached is started.
  service: name=memcached state=restarted enabled=yes