---
# Install memcached

- name: Ensure memcached is installed.
  apt:
    pkg: memcached
    state: present
    
- name: Copy memcached configuration in place.
  template:
    src: memcached.conf.j2
    dest: "/etc/memcached.conf"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Copy startup script in place.
  template:
    src: startup.sh.j2
    dest: "/opt/run-parts/memcached"
    owner: root
    group: root
    mode: 0555
    force: yes