---
# Install NodeJS

- name: Add repository key for NodeJS repository.
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
  
- name: Add repository for NodeJS.
  apt_repository: repo='deb https://deb.nodesource.com/node_{{ nodejs_version }} jessie main' state=present
  
- name: Add source repository for NodeJS.
  apt_repository: repo='deb-src https://deb.nodesource.com/node_{{ nodejs_version }} jessie main' state=present
  
- name: Pin Node packages.
  template:
    src: nodesource.pref.j2
    dest: "/etc/apt/preferences.d/nodesource.pref"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Update apt cache.
  apt: update_cache=yes
  
- name: Ensure mysql is installed.
  apt:
    pkg: "nodejs"
    state: latest