---

- name: Ensure python-pip is installed.
  apt:
    pkg: python-pip
    state: present

- name: Install mkdocs via pip.
  command: >
    pip install mkdocs

- name: Check if we already have a docs directory.
  stat: path="{{ project_dir }}/docs"
  register: docs_generate
  
- name: Generates docs skeleton if none found.
  command: >
    mkdocs new /vagrant
  become: true
  become_user: vagrant
  when: not docs_generate.stat.exists

- name: Copy landing page section.
  template:
    src: "section.html.j2"
    dest: "{{ ce_vm_webroot }}/includes/mkdocs.html"
    force: yes

- name: Copy startup script in place.
  template:
    src: startup.sh.j2
    dest: "/opt/run-parts/mkdocs"
    owner: root
    group: root
    mode: 0555
    force: yes