---
# (Re) install nginx

- name: Add DotDeb repository key for NGINX.
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present

- name: Add DotDeb repository.
  apt_repository: repo='deb http://packages.dotdeb.org jessie all' state=present

- name: Pin Nginx packages.
  template:
    src: dotdeb.pref.j2
    dest: "/etc/apt/preferences.d/dotdeb.pref"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Ensure nginx is installed.
  apt:
    pkg: nginx
    state: present

- name: Create SSL certificates folder
  file:
    path: '/etc/nginx/ssl'
    owner: 'root'
    group: 'root'
    state: directory

- name: Copy SSL certificate.
  template:
    src: ce-vm-self.crt
    dest: "/etc/nginx/ssl/ce-vm-self.crt"
    owner: root
    group: root
    mode: 0666

- name: Copy SSL key.
  template:
    src: ce-vm-self.key
    dest: "/etc/nginx/ssl/ce-vm-self.key"
    owner: root
    group: root
    mode: 0666

- name: Copy project vhost in place.
  template:
    src: vhosts.j2
    dest: "/etc/nginx/sites-enabled/{{ project_name }}.conf"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Copy project type-specific configuration in place.  
  template:
    src: "{{ project_type }}.j2"
    dest: "/etc/nginx/conf.d/{{ project_type }}"
    owner: root
    group: root
    mode: 0644
    force: yes

- file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Copy landing page section.
  template:
    src: "section.html.j2"
    dest: "{{ ce_vm_webroot }}/includes/nginx.html"
    force: yes

- name: Copy startup script in place.
  template:
    src: startup.sh.j2
    dest: "/opt/run-parts/nginx"
    owner: root
    group: root
    mode: 0555
    force: yes