---

- hosts: all
  become: yes
  
  pre_tasks:
    
    - set_fact: request_time="{{lookup('pipe','date +%Y%m%d%H%M%S')}}"  
  
    - include_vars: "{{ item }}"
      with_fileglob: "{{ config_files }}"
    
    - name: Run init tasks
      include: tasks/init-debian.yml
    
  roles:
    
    - { role: ce.postfix }
    - { role: ce.mysql }