---

- hosts: all
  become: yes

  pre_tasks:
    
    - include_vars: "{{ item }}"
      with_fileglob: "{{ config_files }}"
    
    - name: Run init tasks
      include: tasks/init-debian.yml
    
  roles:
    
    - { role: ce.mysql }